site_name: Scripting Bible
theme:
  name: material

  palette:
    primary: black
    accent: cyan
    scheme: slate
  font:
    text: "Verdana"
    code: "JetBrains Mono"

  language: en
  
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences